-- CREATE TABLE turnover
-- (
--     ID         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     branch_id  int      not null, --ID филиала
--     good_id    INT      NOT NULL, --ID товара
--     oper_date  DATE     NOT NULL, --дата операции
--     oper_type  SMALLINT NOT NULL, --тип операции 1 - приход, 0 - расход
--     good_count INT      NOT NULL  --количество товара в результате операции
-- );
-- INSERT into turnover (branch_id, good_id, oper_date, oper_type, good_count)
-- VALUES (1, 1, '20200201 10:05:25', 1, 20),
--        (2, 1, '20200201 11:24:48', 1, 10),
--        (1, 2, '20200201 10:20:38', 1, 15),
--        (1, 1, '20200201 14:26:28', 0, 4),
--        (2, 1, '20200204 11:48:29', 0, 8),
--        (1, 1, '20200205 20:13:57', 0, 9),
--        (1, 1, '20200206 16:15:38', 1, 4),
--        (1, 1, '20200215 09:00:26', 0, 10),
--        (2, 1, '20200216 12:27:59', 0, 2),
--        (1, 1, '20200217 22:16:36', 0, 1),
--        (1, 2, '20200219 14:28:49', 0, 5),
--        (1, 1, '20200301 14:25:36', 1, 10),
--        (2, 1, '20200301 15:26:36', 1, 10),
--        (1, 2, '20200305 11:12:34', 0, 10),
--        (2, 1, '20200307 16:16:46', 0, 7);


WITH m AS (SELECT t.good_id,
                  t.oper_date,
                  (SELECT DISTINCT sum(good_count) FILTER (WHERE oper_type = 1 ) OVER (PARTITION BY good_id) -
                                   sum(good_count) FILTER (WHERE oper_type = 0 ) OVER (PARTITION BY good_id)
                   FROM (SELECT * FROM turnover WHERE oper_date <= t.oper_date AND good_id = t.good_id)) AS gcount,
                  (SELECT MIN(oper_date)
                   FROM turnover
                   WHERE good_id = t.good_id
                     AND oper_date > t.oper_date
                     AND oper_type = 1)                                                                  AS min
           FROM turnover AS t)
SELECT good_id, oper_date AS start, min AS end
FROM m
WHERE gcount = 0;